# Store Type creation script using kfutil
# Generated by Doctool

Write-Host "Creating store type: RFJKS"
kfutil store-types create RFJKS

Write-Host "Creating store type: RFPEM"
kfutil store-types create RFPEM

Write-Host "Creating store type: RFPkcs12"
kfutil store-types create RFPkcs12

Write-Host "Creating store type: RFDER"
kfutil store-types create RFDER

Write-Host "Creating store type: RFKDB"
kfutil store-types create RFKDB

Write-Host "Creating store type: RFORA"
kfutil store-types create RFORA

