# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: RFJKS"
$Body = @'
{
  "Name": "RFJKS",
  "ShortName": "RFJKS",
  "Capability": "RFJKS",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A username (or valid PAM key if the username is stored in a KF Command configured PAM integration). If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A password (or valid PAM key if the password is stored in a KF Command configured PAM integration). The password can also be an SSH private key if connecting via SSH to a server using SSH private key authentication. If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFilePermissionsOnStoreCreation field should contain a three-digit value between 000 and 777 representing the Linux file permissions to be set for the certificate store upon creation. Example: '600' or '755'.  Overrides DefaultLinuxPermissionOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFileOwnerOnStoreCreation field should contain a valid user ID recognized by the destination Linux server, optionally followed by a colon and a group ID if the group owner differs. Example: 'userID' or 'userID:groupID'.  Overrides DefaultOwnerOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The SudoImpersonatingUser field should contain a valid user ID to impersonate using sudo on the destination Linux server. Example: 'impersonatedUserID'.  Overrides DefaultSudoImpersonatedUser [config.json](#post-installation) setting."
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Remove root certificate from chain when adding/renewing a certificate in a store."
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "Integer value representing the port that should be used when connecting to Linux servers over SSH.  Overrides SSHPort [config.json](#post-installation) setting."
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True",
      "Description": "Recommended to be set to the default value of 'Y'.  For a detailed explanation of this setting, please refer to [Use Shell Commands Setting](#use-shell-commands-setting)"
    },
    {
      "Name": "PostJobApplicationRestart",
      "DisplayName": "Post Job Application Restart",
      "Required": false,
      "DependsOn": "",
      "Type": "MultipleChoice",
      "DefaultValue": "Apache Tomcat Restart,Jetty Restart",
      "Description": "Select the command to be run after a Management Add or ODKG job executes.  Leave unselected if no command is desired."
    },
    {
      "Name": "RequiresLegacyEncryption",
      "DisplayName": "Requires Legacy Encryption",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Optional setting.  If set to true, PkcsObjectIdentifiers.PbeWithShaAnd3KeyTripleDesCbc and PkcsObjectIdentifiers.PbewithShaAnd40BitRC2Cbc algorithms will be used to create the underlying BouncyCastle Pkcs12Store used to feed the certificate store being managed during Management jobs.  Should be left not implemented or set to False for most instances."
    }
  ],
  "EntryParameters": []
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: RFPEM"
$Body = @'
{
  "Name": "RFPEM",
  "ShortName": "RFPEM",
  "Capability": "RFPEM",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store.  For stores with PKCS#8 private keys, set the password for encrypted private keys (BEGIN ENCRYPTED PRIVATE KEY) or 'No Value' for unencrypted private keys (BEGIN PRIVATE KEY).  If managing a store with a PKCS#1 private key (BEGIN RSA PRIVATE KEY), this value MUST be set to 'No Value'",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A username (or valid PAM key if the username is stored in a KF Command configured PAM integration). If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A password (or valid PAM key if the password is stored in a KF Command configured PAM integration). The password can also be an SSH private key if connecting via SSH to a server using SSH private key authentication. If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFilePermissionsOnStoreCreation field should contain a three-digit value between 000 and 777 representing the Linux file permissions to be set for the certificate store upon creation. Example: '600' or '755'.  Overrides DefaultLinuxPermissionOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFileOwnerOnStoreCreation field should contain a valid user ID recognized by the destination Linux server, optionally followed by a colon and a group ID if the group owner differs. Example: 'userID' or 'userID:groupID'.  Overrides DefaultOwnerOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The SudoImpersonatingUser field should contain a valid user ID to impersonate using sudo on the destination Linux server. Example: 'impersonatedUserID'.  Overrides [config.json](#post-installation) DefaultSudoImpersonatedUser setting.."
    },
    {
      "Name": "IsTrustStore",
      "DisplayName": "Trust Store",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "false",
      "Description": "The IsTrustStore field should contain a boolean value ('true' or 'false') indicating whether the store will be identified as a trust store, which can hold multiple certificates without private keys. Example: 'true' for a trust store or 'false' for a store with a single certificate and private key."
    },
    {
      "Name": "IncludesChain",
      "DisplayName": "Store Includes Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "false",
      "Description": "The IncludesChain field should contain a boolean value ('true' or 'false') indicating whether the certificate store includes the full certificate chain along with the end entity certificate. Example: 'true' to include the full chain or 'false' to exclude it."
    },
    {
      "Name": "SeparatePrivateKeyFilePath",
      "DisplayName": "Separate Private Key File Location",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The SeparatePrivateKeyFilePath field should contain the full path and file name where the separate private key file will be stored if it is to be kept outside the main certificate file. Example: '/path/to/privatekey.pem'."
    },
    {
      "Name": "IgnorePrivateKeyOnInventory",
      "DisplayName": "Ignore Private Key On Inventory",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "false",
      "Description": "The IgnorePrivateKeyOnInventory field should contain a boolean value ('true' or 'false') indicating whether to disregard the private key during inventory. Setting this to 'true' will allow inventory for the store without needing to supply the location of the private key or the password if the key is encrypted.  However, doing this makes the store in effect inventory-only and no management jobs will be able to be run for this store. Example: 'true' to ignore the private key or 'false' to include it."
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Remove root certificate from chain when adding/renewing a certificate in a store."
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "Integer value representing the port that should be used when connecting to Linux servers over SSH.  Overrides SSHPort [config.json](#post-installation) setting."
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True",
      "Description": "Recommended to be set to the default value of 'Y'.  For a detailed explanation of this setting, please refer to [Use Shell Commands Setting](#use-shell-commands-setting)"
    },
    {
      "Name": "PostJobApplicationRestart",
      "DisplayName": "Post Job Application Restart",
      "Required": false,
      "DependsOn": "",
      "Type": "MultipleChoice",
      "DefaultValue": "Apache HTTPD Restart,NGNIX Restart,HAProxy Restart,Envoy Proxy Restart",
      "Description": "Select the command to be run after a Management Add or ODKG job executes.  Leave unselected if no command is desired."
    },
    {
      "Name": "RequiresLegacyEncryption",
      "DisplayName": "Requires Legacy Encryption",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Optional setting.  If set to true, PkcsObjectIdentifiers.PbeWithShaAnd3KeyTripleDesCbc and PkcsObjectIdentifiers.PbewithShaAnd40BitRC2Cbc algorithms will be used to create the underlying BouncyCastle Pkcs12Store used to feed the certificate store being managed during Management jobs.  Should be left not implemented or set to False for most instances."
    }
  ],
  "EntryParameters": []
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: RFPkcs12"
$Body = @'
{
  "Name": "RFPkcs12",
  "ShortName": "RFPkcs12",
  "Capability": "RFPkcs12",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A username (or valid PAM key if the username is stored in a KF Command configured PAM integration). If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A password (or valid PAM key if the password is stored in a KF Command configured PAM integration). The password can also be an SSH private key if connecting via SSH to a server using SSH private key authentication. If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFilePermissionsOnStoreCreation field should contain a three-digit value between 000 and 777 representing the Linux file permissions to be set for the certificate store upon creation. Example: '600' or '755'.  Overrides DefaultLinuxPermissionOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFileOwnerOnStoreCreation field should contain a valid user ID recognized by the destination Linux server, optionally followed by a colon and a group ID if the group owner differs. Example: 'userID' or 'userID:groupID'.  Overrides DefaultOwnerOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The SudoImpersonatingUser field should contain a valid user ID to impersonate using sudo on the destination Linux server. Example: 'impersonatedUserID'.  Overrides DefaultSudoImpersonatedUser [config.json](#post-installation) setting."
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Remove root certificate from chain when adding/renewing a certificate in a store."
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "Integer value representing the port that should be used when connecting to Linux servers over SSH.  Overrides SSHPort [config.json](#post-installation) setting."
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True",
      "Description": "Recommended to be set to the default value of 'Y'.  For a detailed explanation of this setting, please refer to [Use Shell Commands Setting](#use-shell-commands-setting)"
    },
    {
      "Name": "RequiresLegacyEncryption",
      "DisplayName": "Requires Legacy Encryption",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Optional setting.  If set to true, PkcsObjectIdentifiers.PbeWithShaAnd3KeyTripleDesCbc and PkcsObjectIdentifiers.PbewithShaAnd40BitRC2Cbc algorithms will be used to create the underlying BouncyCastle Pkcs12Store used to feed the certificate store being managed during Management jobs.  Should be left not implemented or set to False for most instances."
    }
  ],
  "EntryParameters": []
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: RFDER"
$Body = @'
{
  "Name": "RFDER",
  "ShortName": "RFDER",
  "Capability": "RFDER",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A username (or valid PAM key if the username is stored in a KF Command configured PAM integration). If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A password (or valid PAM key if the password is stored in a KF Command configured PAM integration). The password can also be an SSH private key if connecting via SSH to a server using SSH private key authentication. If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFilePermissionsOnStoreCreation field should contain a three-digit value between 000 and 777 representing the Linux file permissions to be set for the certificate store upon creation. Example: '600' or '755'.  Overrides DefaultLinuxPermissionOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFileOwnerOnStoreCreation field should contain a valid user ID recognized by the destination Linux server, optionally followed by a colon and a group ID if the group owner differs. Example: 'userID' or 'userID:groupID'.  Overrides DefaultOwnerOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The SudoImpersonatingUser field should contain a valid user ID to impersonate using sudo on the destination Linux server. Example: 'impersonatedUserID'.  Overrides [config.json](#post-installation) DefaultSudoImpersonatedUser setting."
    },
    {
      "Name": "SeparatePrivateKeyFilePath",
      "DisplayName": "Separate Private Key File Location",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The SeparatePrivateKeyFilePath field should contain the full path and file name where the separate private key file will be stored if it is to be kept outside the main certificate file. Example: '/path/to/privatekey.der'."
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Remove root certificate from chain when adding/renewing a certificate in a store."
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "Integer value representing the port that should be used when connecting to Linux servers over SSH.  Overrides SSHPort [config.json](#post-installation) setting."
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True",
      "Description": "Recommended to be set to the default value of 'Y'.  For a detailed explanation of this setting, please refer to [Use Shell Commands Setting](#use-shell-commands-setting)"
    },
    {
      "Name": "RequiresLegacyEncryption",
      "DisplayName": "Requires Legacy Encryption",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Optional setting.  If set to true, PkcsObjectIdentifiers.PbeWithShaAnd3KeyTripleDesCbc and PkcsObjectIdentifiers.PbewithShaAnd40BitRC2Cbc algorithms will be used to create the underlying BouncyCastle Pkcs12Store used to feed the certificate store being managed during Management jobs.  Should be left not implemented or set to False for most instances."
    }
  ],
  "EntryParameters": []
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: RFKDB"
$Body = @'
{
  "Name": "RFKDB",
  "ShortName": "RFKDB",
  "Capability": "RFKDB",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A username (or valid PAM key if the username is stored in a KF Command configured PAM integration). If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A password (or valid PAM key if the password is stored in a KF Command configured PAM integration). The password can also be an SSH private key if connecting via SSH to a server using SSH private key authentication. If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFilePermissionsOnStoreCreation field should contain a three-digit value between 000 and 777 representing the Linux file permissions to be set for the certificate store upon creation. Example: '600' or '755'.  Overrides DefaultLinuxPermissionOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFileOwnerOnStoreCreation field should contain a valid user ID recognized by the destination Linux server, optionally followed by a colon and a group ID if the group owner differs. Example: 'userID' or 'userID:groupID'.  Overrides DefaultOwnerOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The SudoImpersonatingUser field should contain a valid user ID to impersonate using sudo on the destination Linux server. Example: 'impersonatedUserID'.  Overrides [config.json](#post-installation) DefaultSudoImpersonatedUser setting."
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Remove root certificate from chain when adding/renewing a certificate in a store."
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "Integer value representing the port that should be used when connecting to Linux servers over SSH.  Overrides SSHPort [config.json](#post-installation) setting."
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True",
      "Description": "Recommended to be set to the default value of 'Y'.  For a detailed explanation of this setting, please refer to [Use Shell Commands Setting](#use-shell-commands-setting)"
    },
    {
      "Name": "RequiresLegacyEncryption",
      "DisplayName": "Requires Legacy Encryption",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Optional setting.  If set to true, PkcsObjectIdentifiers.PbeWithShaAnd3KeyTripleDesCbc and PkcsObjectIdentifiers.PbewithShaAnd40BitRC2Cbc algorithms will be used to create the underlying BouncyCastle Pkcs12Store used to feed the certificate store being managed during Management jobs.  Should be left not implemented or set to False for most instances."
    }
  ],
  "EntryParameters": []
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: RFORA"
$Body = @'
{
  "Name": "RFORA",
  "ShortName": "RFORA",
  "Capability": "RFORA",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A username (or valid PAM key if the username is stored in a KF Command configured PAM integration). If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "A password (or valid PAM key if the password is stored in a KF Command configured PAM integration). The password can also be an SSH private key if connecting via SSH to a server using SSH private key authentication. If acting as an *agent* using local file access, just check *No Value*"
    },
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFilePermissionsOnStoreCreation field should contain a three-digit value between 000 and 777 representing the Linux file permissions to be set for the certificate store upon creation. Example: '600' or '755'.  Overrides DefaultLinuxPermissionOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The LinuxFileOwnerOnStoreCreation field should contain a valid user ID recognized by the destination Linux server, optionally followed by a colon and a group ID if the group owner differs. Example: 'userID' or 'userID:groupID'.  Overrides DefaultOwnerOnStoreCreation [config.json](#post-installation) setting."
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The SudoImpersonatingUser field should contain a valid user ID to impersonate using sudo on the destination Linux server. Example: 'impersonatedUserID'.  Overrides [config.json](#post-installation) DefaultSudoImpersonatedUser setting."
    },
    {
      "Name": "WorkFolder",
      "DisplayName": "Location to use for creation/removal of work files",
      "Required": true,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "The WorkFolder field should contain the path on the managed server where temporary work files can be created, modified, and deleted during Inventory and Management jobs. Example: '/path/to/workfolder'."
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Remove root certificate from chain when adding/renewing a certificate in a store."
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Internally set the -IncludePortInSPN option when creating the remote PowerShell connection. Needed for some Kerberos configurations."
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": "",
      "Description": "Integer value representing the port that should be used when connecting to Linux servers over SSH.  Overrides SSHPort [config.json](#post-installation) setting."
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True",
      "Description": "Recommended to be set to the default value of 'Y'.  For a detailed explanation of this setting, please refer to [Use Shell Commands Setting](#use-shell-commands-setting)"
    },
    {
      "Name": "RequiresLegacyEncryption",
      "DisplayName": "Requires Legacy Encryption",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False",
      "Description": "Optional setting.  If set to true, PkcsObjectIdentifiers.PbeWithShaAnd3KeyTripleDesCbc and PkcsObjectIdentifiers.PbewithShaAnd40BitRC2Cbc algorithms will be used to create the underlying BouncyCastle Pkcs12Store used to feed the certificate store being managed during Management jobs.  Should be left not implemented or set to False for most instances."
    }
  ],
  "EntryParameters": []
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

