#!/usr/bin/env bash

# Creates all 6 store types via the Keyfactor Command REST API using curl.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if [ -z "${KEYFACTOR_HOSTNAME}" ]; then
    echo "ERROR: KEYFACTOR_HOSTNAME is required"
    exit 1
fi

BASE_URL="https://${KEYFACTOR_HOSTNAME}/keyfactorapi"

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if [ -n "${KEYFACTOR_AUTH_ACCESS_TOKEN}" ]; then
    BEARER_TOKEN="${KEYFACTOR_AUTH_ACCESS_TOKEN}"
elif [ -n "${KEYFACTOR_AUTH_CLIENT_ID}" ] && [ -n "${KEYFACTOR_AUTH_CLIENT_SECRET}" ] && [ -n "${KEYFACTOR_AUTH_TOKEN_URL}" ]; then
    echo "Fetching OAuth token..."
    BEARER_TOKEN=$(curl -s -X POST "${KEYFACTOR_AUTH_TOKEN_URL}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=${KEYFACTOR_AUTH_CLIENT_ID}" \
        --data-urlencode "client_secret=${KEYFACTOR_AUTH_CLIENT_SECRET}" | jq -r '.access_token')
    if [ -z "${BEARER_TOKEN}" ] || [ "${BEARER_TOKEN}" = "null" ]; then
        echo "ERROR: Failed to fetch OAuth token from ${KEYFACTOR_AUTH_TOKEN_URL}"
        exit 1
    fi
elif [ -n "${KEYFACTOR_USERNAME}" ] && [ -n "${KEYFACTOR_PASSWORD}" ] && [ -n "${KEYFACTOR_DOMAIN}" ]; then
    BEARER_TOKEN=""
else
    echo "ERROR: Authentication required. Set one of:"
    echo "  KEYFACTOR_AUTH_ACCESS_TOKEN"
    echo "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL"
    echo "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN"
    exit 1
fi

if [ -n "${BEARER_TOKEN}" ]; then
    CURL_AUTH=("-H" "Authorization: Bearer ${BEARER_TOKEN}")
else
    CURL_AUTH=("-u" "${KEYFACTOR_USERNAME}@${KEYFACTOR_DOMAIN}:${KEYFACTOR_PASSWORD}")
fi

create_store_type() {
    local name="$1"
    local body="$2"
    echo "Creating ${name} store type..."
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${BASE_URL}/certificatestoretypes" \
        -H "Content-Type: application/json" \
        -H "x-keyfactor-requested-with: APIClient" \
        "${CURL_AUTH[@]}" \
        -d "${body}")
    if [ "$response" = "200" ] || [ "$response" = "201" ]; then
        echo "  OK (HTTP ${response})"
    else
        echo "  FAILED (HTTP ${response})"
    fi
}

# ---------------------------------------------------------------------------
# RFJKS — The IP address or DNS of the server hosting the certificate store.  For more information, see [Client Machine ](#client-machine-instructions)
# ---------------------------------------------------------------------------
create_store_type "RFJKS" '{
  "Name": "RFJKS",
  "ShortName": "RFJKS",
  "Capability": "RFJKS",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True"
    },
    {
      "Name": "PostJobApplicationRestart",
      "DisplayName": "Post Job Application Restart",
      "Required": false,
      "DependsOn": "",
      "Type": "MultipleChoice",
      "DefaultValue": "Apache Tomcat Restart,Jetty Restart"
    }
  ],
  "EntryParameters": [],
  "StorePathDescription": "The full path and file name, including file extension if one exists where the certificate store file is located.  For Linux orchestrated servers, StorePath will begin with a forward slash (i.e. /folder/path/storename.ext).  For Windows orchestrated servers, it should begin with a drive letter (i.e. c:\\folder\\path\\storename.ext)."
}'

# ---------------------------------------------------------------------------
# RFPEM — The Client Machine field should contain the DNS name or IP address of the remote orchestrated server for Linux orchestrated servers, formatted as a URL (protocol://dns-or-ip:port) for Windows orchestrated servers, or '1.1.1.1|LocalMachine' for local agents. Example: 'https://myserver.mydomain.com:5986' or '1.1.1.1|LocalMachine' for local access.
# ---------------------------------------------------------------------------
create_store_type "RFPEM" '{
  "Name": "RFPEM",
  "ShortName": "RFPEM",
  "Capability": "RFPEM",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store.  For stores with PKCS#8 private keys, set the password for encrypted private keys (BEGIN ENCRYPTED PRIVATE KEY) or 'No Value' for unencrypted private keys (BEGIN PRIVATE KEY).  If managing a store with a PKCS#1 private key (BEGIN RSA PRIVATE KEY), this value MUST be set to 'No Value'",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "IsTrustStore",
      "DisplayName": "Trust Store",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "false"
    },
    {
      "Name": "IncludesChain",
      "DisplayName": "Store Includes Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "false"
    },
    {
      "Name": "SeparatePrivateKeyFilePath",
      "DisplayName": "Separate Private Key File Location",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "IgnorePrivateKeyOnInventory",
      "DisplayName": "Ignore Private Key On Inventory",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "false"
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True"
    },
    {
      "Name": "PostJobApplicationRestart",
      "DisplayName": "Post Job Application Restart",
      "Required": false,
      "DependsOn": "",
      "Type": "MultipleChoice",
      "DefaultValue": "Apache HTTPD Restart,NGNIX Restart,HAProxy Restart,Envoy Proxy Restart"
    }
  ],
  "EntryParameters": [],
  "StorePathDescription": "The Store Path field should contain the full path and file name, including file extension if applicable, beginning with a forward slash (/) for Linux orchestrated servers or a drive letter (i.e., c:\\folder\\path\\storename.ext) for Windows orchestrated servers. Example: '/folder/path/storename.pem' or 'c:\\folder\\path\\storename.pem'."
}'

# ---------------------------------------------------------------------------
# RFPkcs12 — The Client Machine field should contain the DNS name or IP address of the remote orchestrated server for Linux orchestrated servers, formatted as a URL (protocol://dns-or-ip:port) for Windows orchestrated servers, or '1.1.1.1|LocalMachine' for local agents. Example: 'https://myserver.mydomain.com:5986' or '1.1.1.1|LocalMachine' for local access.
# ---------------------------------------------------------------------------
create_store_type "RFPkcs12" '{
  "Name": "RFPkcs12",
  "ShortName": "RFPkcs12",
  "Capability": "RFPkcs12",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True"
    }
  ],
  "EntryParameters": [],
  "StorePathDescription": "The Store Path field should contain the full path and file name, including file extension if applicable, beginning with a forward slash (/) for Linux orchestrated servers or a drive letter (i.e., c:\\folder\\path\\storename.p12) for Windows orchestrated servers. Example: '/folder/path/storename.p12' or 'c:\\folder\\path\\storename.p12'."
}'

# ---------------------------------------------------------------------------
# RFDER — The Client Machine field should contain the DNS name or IP address of the remote orchestrated server for Linux orchestrated servers, formatted as a URL (protocol://dns-or-ip:port) for Windows orchestrated servers, or '1.1.1.1|LocalMachine' for local agents. Example: 'https://myserver.mydomain.com:5986' or '1.1.1.1|LocalMachine' for local access.
# ---------------------------------------------------------------------------
create_store_type "RFDER" '{
  "Name": "RFDER",
  "ShortName": "RFDER",
  "Capability": "RFDER",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Forbidden",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": true,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "SeparatePrivateKeyFilePath",
      "DisplayName": "Separate Private Key File Location",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True"
    }
  ],
  "EntryParameters": [],
  "StorePathDescription": "The Store Path field should contain the full path and file name, including file extension if applicable, beginning with a forward slash (/) for Linux orchestrated servers or a drive letter (i.e., c:\\folder\\path\\storename.der) for Windows orchestrated servers. Example: '/folder/path/storename.der' or 'c:\\folder\\path\\storename.der'."
}'

# ---------------------------------------------------------------------------
# RFKDB — The Client Machine field should contain the DNS name or IP address of the remote orchestrated server for Linux orchestrated servers, formatted as a URL (protocol://dns-or-ip:port) for Windows orchestrated servers, or '1.1.1.1|LocalMachine' for local agents. Example: 'https://myserver.mydomain.com:5986' or '1.1.1.1|LocalMachine' for local access.
# ---------------------------------------------------------------------------
create_store_type "RFKDB" '{
  "Name": "RFKDB",
  "ShortName": "RFKDB",
  "Capability": "RFKDB",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True"
    }
  ],
  "EntryParameters": [],
  "StorePathDescription": "The Store Path field should contain the full path and file name, including file extension if applicable, beginning with a forward slash (/) for Linux orchestrated servers or a drive letter (i.e., c:\\folder\\path\\storename.kdb) for Windows orchestrated servers. Example: '/folder/path/storename.kdb' or 'c:\\folder\\path\\storename.kdb'."
}'

# ---------------------------------------------------------------------------
# RFORA — The Client Machine field should contain the DNS name or IP address of the remote orchestrated server for Linux orchestrated servers, formatted as a URL (protocol://dns-or-ip:port) for Windows orchestrated servers, or '1.1.1.1|LocalMachine' for local agents. Example: 'https://myserver.mydomain.com:5986' or '1.1.1.1|LocalMachine' for local access.
# ---------------------------------------------------------------------------
create_store_type "RFORA" '{
  "Name": "RFORA",
  "ShortName": "RFORA",
  "Capability": "RFORA",
  "ServerRequired": true,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": true,
    "StorePassword": {
      "Description": "Password used to secure the Certificate Store",
      "IsPAMEligible": true
    }
  },
  "Properties": [
    {
      "Name": "LinuxFilePermissionsOnStoreCreation",
      "DisplayName": "Linux File Permissions on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "LinuxFileOwnerOnStoreCreation",
      "DisplayName": "Linux File Owner on Store Creation",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "SudoImpersonatingUser",
      "DisplayName": "Sudo Impersonating User",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "WorkFolder",
      "DisplayName": "Location to use for creation/removal of work files",
      "Required": true,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "RemoveRootCertificate",
      "DisplayName": "Remove Root Certificate from Chain",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "IncludePortInSPN",
      "DisplayName": "Include Port in SPN for WinRM",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "False"
    },
    {
      "Name": "SSHPort",
      "DisplayName": "SSH Port",
      "Required": false,
      "DependsOn": "",
      "Type": "String",
      "DefaultValue": ""
    },
    {
      "Name": "UseShellCommands",
      "DisplayName": "Use Shell Commands",
      "Required": false,
      "DependsOn": "",
      "Type": "Bool",
      "DefaultValue": "True"
    }
  ],
  "EntryParameters": [],
  "StorePathDescription": "The Store Path field should contain the full path and file name of the Oracle Wallet, including the 'eWallet.p12' file name by convention. Example: '/path/to/eWallet.p12' or 'c:\\path\\to\\eWallet.p12'."
}'


echo "Completed."
