#!/bin/bash
# Store Type creation script using kfutil
# Generated by Doctool

set -e

echo "Creating store type: RFJKS"
kfutil store-types create RFJKS

echo "Creating store type: RFPEM"
kfutil store-types create RFPEM

echo "Creating store type: RFPkcs12"
kfutil store-types create RFPkcs12

echo "Creating store type: RFDER"
kfutil store-types create RFDER

echo "Creating store type: RFKDB"
kfutil store-types create RFKDB

echo "Creating store type: RFORA"
kfutil store-types create RFORA

